# Generated by Django 4.0.1 on 2025-01-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_becado',
            old_name='cede',
            new_name='sede',
        ),
    ]
