# Generated by Django 4.0.1 on 2025-01-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdell', '0002_rename_cede_registro_becado_sede'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
