# Generated by Django 4.0.1 on 2025-01-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdell', '0003_delete_comentarios_delete_producto_delete_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_becado',
            name='apellido2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registro_becado',
            name='edad',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro_becado',
            name='nombre2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
